// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wqcehmheubecmwoykbtf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndxY2VobWhldWJlY213b3lrYnRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NjMyNDksImV4cCI6MjA3MDEzOTI0OX0.96GE219opuHxpJ0xCfsB7T7EHpdAcie82FtvgEHdAv0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});